### ISSUE TITLE
error al compilar 

### ISSUE THREAD

**Issue by tusanalejo** [llullutuqo/katakuntur#1]
![errorkata](https://cloud.githubusercontent.com/assets/25067121/23051822/f6faaf4c-f499-11e6-8949-3fffbbef8063.png)

Despues de la sentencia make ocurre un problema referente a la clase QGraphicsItem, por cierto mi sistema es ubuntu. Saludos.

**Comment by llullutuqo** [comment]
¿qué versión de gcc estas usando?

**Comment by llullutuqo** [comment]
Ya esta corregido en la última confirmación de código.
